// Typelizer digest a48cac8cf7c1ff39aba9e0c7650afd2f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Category = {
  id: number;
  name: string;
  created_at: string;
  updated_at: string;
}

export default Category;
