// Typelizer digest 3e0002de85540251bafeb20b05fceed5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface Category {
  id: string
  name: string
  created_at: string
  updated_at: string
}

export default Category
