// Typelizer digest 780236e49ab137a3e557ece00654e3c9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type { default as Post } from './Post'
export type { default as User } from './User'
