// Typelizer digest 41299a9fe65e3f229f60e6a6fef51b04
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Post = {
  id: number;
  title: string | null;
  body: string | null;
  content: string | null;
  created_at: string;
  updated_at: string;
  post_cover_url: string | null;
  user: {
    id: number;
    name: string | null;
    profile_tagline: string | null;
    avatar_url: string | null;
  };
  category_name: string | null;
  sub_title: string | null;
}

export default Post;
