// Typelizer digest 96731fb48e59994c7d2a6f20a86128de
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {User} from '@/types'

type Post = {
  id: number;
  title: string | null;
  body: string | null;
  content: string | null;
  sub_title: string | null;
  created_at: string;
  updated_at: string;
  category_id: number;
  status: "draft" | "preview" | "published" | null;
  user_id: number;
  likes_count: unknown;
  likers_info: unknown;
  category_name: unknown;
  post_cover_url: unknown;
  user: User;
}

export default Post;
