// Typelizer digest 41299a9fe65e3f229f60e6a6fef51b04
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Post = {
  id: number;
  title: string | null;
  body: string | null;
  content: string | null;
  created_at: string;
  updated_at: string;
}

export default Post;
