// Typelizer digest a8e88d0f389ee493edb119d561bc5316
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Session = {
  email: unknown;
  password: unknown;
  password_confirmation: unknown;
}

export default Session;
