// Typelizer digest 9aaec0fcb0c2b62a76c1cbd88e7aee64
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface User {
  id: number
  name: unknown
  email: string
  created_at: string
  updated_at: string
}

export default User
