// Typelizer digest 9aaec0fcb0c2b62a76c1cbd88e7aee64
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

interface User {
  id: number
  name: unknown
  email: string
  created_at: string
  updated_at: string
  avatar_url: string
  profile_bio: string
  location: string
  tech_stacks: unknown | unknown[]
  social_profiles: unknown | unknown[]
  user_id: number
  profile_tagline: string
  admin: boolean
}

export default User
