// Typelizer digest ce0c9579d85ab60414486244bfbd97c5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: unknown;
  avatar_url: unknown;
}

export default User;
